### ISSUE TITLE
zones 30 : continuer la zone 30 goutte d'or jusqu'à la rue Marx Dormoy

### ISSUE THREAD

**Issue by prigaux** [ParisEnSelle/planvelo-carte#2]
Rues concernées : 
- rue Doudeauville
- rue de Jessaint
- rue Jean François Lépine
- rue Jean Robert

**Comment by prigaux** [comment]
Voir notamment les rues à 30 sur openstreetmap : http://overpass-turbo.eu/s/mOS

**Comment by jeekajoo** [comment]
merci

**Comment by prigaux** [comment]
Zut, je n'ai pas été assez clair : la rue Stephenson, la rue de Jessain, la rue de Tombouctou sont dans la zone 30.

**Comment by jeekajoo** [comment]
Elles y sont. Sauf la rue de Jessain, pas entièrement englobée jusqu'à place de la chapelle.

**Comment by jeekajoo** [comment]
D'une manière générale, les PR sont bienvenues :)

**Comment by prigaux** [comment]
Dur dur geojson.io pour modifier des polygones :-/

**Comment by jeekajoo** [comment]
Oui c'est vrai. Surtout parce qu'il y a un bug dans geojson.io. Seuls certains polygones se retrouvent éditables. cc @Loufylouf 

![](https://lut.im/sYnRasEmKZ/GzYNjjv9odGATrAU)

En attendant tu peux suppr / créer nouveau polygone étendu. Ou juste rajouter un nouveau à coté. Ca fera l'affaire.

**Comment by jeekajoo** [comment]
Nous projetons de contribuer et d'utiliser les données OSM.
Pour en discuter, rdv dans le channel #cartopartie et #carto-plan-velo sur le slack de ParisEnSelle.
