### ISSUE TITLE
planvelo.geojson : gérer les parties du REVe qui existent avant 2015

### ISSUE THREAD

**Issue by prigaux** [ParisEnSelle/planvelo-carte#3]
La piste cyclable bi-directionnelle rue d'Aubervilliers entre la rue du Département et la rue Labois Rouillon existe depuis longtemps. Elle ne sera pas modifiée.

Je propose soit : 
- de supprimer cette portion qui est actuellement en "Plan vélo (projet)"
- de mettre cette portion en une nouvelle couleur "réalisée avant plan vélo 2015-2020"

**Comment by jeekajoo** [comment]
Bonjour @prigaux,
Nous avons intégré les aménagements antérieurs à 2015 dans un nouveau calque `planvelo-anterieur.geojson`.

Merci pour la proposition!
